-- Initial database setup for KanbanFlow
-- This script creates all necessary tables and seed data

-- Create Users table
CREATE TABLE IF NOT EXISTS "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Email" text NOT NULL,
    "FullName" text,
    "PasswordHash" text NOT NULL,
    "Role" text NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

-- Create RefreshTokens table
CREATE TABLE IF NOT EXISTS "RefreshTokens" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Token" text NOT NULL,
    "UserId" integer NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "IsRevoked" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RefreshTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

-- Create Tasks table
CREATE TABLE IF NOT EXISTS "Tasks" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "Description" text,
    "Status" text NOT NULL,
    "Position" integer NOT NULL,
    "UserId" integer NOT NULL,
    "UserName" text NOT NULL,
    "AssignedToUserId" integer,
    "DueDate" timestamp with time zone,
    "Priority" text NOT NULL,
    "Tags" text,
    "Comments" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Tasks" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Tasks_Users_AssignedToUserId" FOREIGN KEY ("AssignedToUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Tasks_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

-- Create TaskHistories table
CREATE TABLE IF NOT EXISTS "TaskHistories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TaskId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "UserName" text NOT NULL,
    "Action" text NOT NULL,
    "OldValue" text,
    "NewValue" text,
    "Details" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_TaskHistories" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TaskHistories_Tasks_TaskId" FOREIGN KEY ("TaskId") REFERENCES "Tasks" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TaskHistories_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

-- Create indexes
CREATE INDEX IF NOT EXISTS "IX_RefreshTokens_UserId" ON "RefreshTokens" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_TaskHistories_TaskId" ON "TaskHistories" ("TaskId");
CREATE INDEX IF NOT EXISTS "IX_TaskHistories_UserId" ON "TaskHistories" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_Tasks_AssignedToUserId" ON "Tasks" ("AssignedToUserId");
CREATE INDEX IF NOT EXISTS "IX_Tasks_UserId" ON "Tasks" ("UserId");

-- Insert seed data
INSERT INTO "Users" ("Id", "Email", "FullName", "PasswordHash", "Role") VALUES
(1, 'doc_js_galindo@fesc.edu.co', 'Admin User', '$2a$11$examplehash', 'Admin'),
(2, 'user@test.com', 'Test User', '$2a$11$examplehash', 'User'),
(3, 'user2@test.com', 'Test User 2', '$2a$11$examplehash', 'User')
ON CONFLICT ("Id") DO NOTHING;

INSERT INTO "Tasks" ("Id", "Title", "Description", "Status", "Position", "UserId", "UserName", "AssignedToUserId", "DueDate", "Priority", "Tags", "Comments", "CreatedAt", "UpdatedAt") VALUES
(1, 'Configurar base de datos', 'Configurar SQL Server y crear migraciones', 'Done', 0, 1, 'doc_js_galindo@fesc.edu.co', NULL, NULL, 'High', NULL, NULL, '2025-11-21 05:00:00+00', '2025-11-25 05:00:00+00'),
(2, 'Implementar autenticación', 'Sistema de login y registro de usuarios', 'InProgress', 0, 2, 'user@test.com', NULL, NULL, 'Medium', NULL, NULL, '2025-11-23 05:00:00+00', '2025-11-26 05:57:06.825+00'),
(3, 'Diseñar interfaz', 'Crear mockups y prototipos de UI', 'ToDo', 0, 3, 'user2@test.com', NULL, '2025-12-02 05:00:00+00', 'Low', 'UI,Design', NULL, '2025-11-25 05:00:00+00', '2025-11-25 05:00:00+00'),
(4, 'Tarea de ejemplo para docente', 'Esta es una tarea de ejemplo para el usuario docente', 'ToDo', 0, 999, 'user999@example.com', NULL, NULL, 'Medium', NULL, NULL, '2025-11-26 05:57:06.825+00', '2025-11-26 05:57:06.825+00')
ON CONFLICT ("Id") DO NOTHING;