// <auto-generated />
using System;
using Kanban.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kanban.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kanban.Core.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Kanban.Core.Entities.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedToUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tags")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId1")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 20, 14, 22, 8, 240, DateTimeKind.Utc).AddTicks(8310),
                            Description = "Configurar PostgreSQL y migraciones",
                            Position = 0,
                            Priority = "High",
                            Status = "Done",
                            Title = "Configurar base de datos",
                            UpdatedAt = new DateTime(2025, 11, 24, 14, 22, 8, 240, DateTimeKind.Utc).AddTicks(8316),
                            UserId = 1,
                            UserName = ""
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 22, 14, 22, 8, 240, DateTimeKind.Utc).AddTicks(8319),
                            Description = "Sistema de login y JWT",
                            Position = 0,
                            Priority = "Medium",
                            Status = "InProgress",
                            Title = "Implementar autenticación",
                            UpdatedAt = new DateTime(2025, 11, 25, 14, 22, 8, 240, DateTimeKind.Utc).AddTicks(8319),
                            UserId = 2,
                            UserName = ""
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 11, 24, 14, 22, 8, 240, DateTimeKind.Utc).AddTicks(8371),
                            Description = "Mockups y diseño UI",
                            DueDate = new DateTime(2025, 12, 2, 14, 22, 8, 240, DateTimeKind.Utc).AddTicks(8368),
                            Position = 0,
                            Priority = "Low",
                            Status = "ToDo",
                            Tags = "UI,Design",
                            Title = "Diseñar interfaz",
                            UpdatedAt = new DateTime(2025, 11, 24, 14, 22, 8, 240, DateTimeKind.Utc).AddTicks(8372),
                            UserId = 3,
                            UserName = ""
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 11, 25, 14, 22, 8, 240, DateTimeKind.Utc).AddTicks(8374),
                            Description = "Tarea especial del profesor",
                            Position = 0,
                            Priority = "Medium",
                            Status = "ToDo",
                            Title = "Tarea para revisión docente",
                            UpdatedAt = new DateTime(2025, 11, 25, 14, 22, 8, 240, DateTimeKind.Utc).AddTicks(8374),
                            UserId = 999,
                            UserName = ""
                        });
                });

            modelBuilder.Entity("Kanban.Core.Entities.TaskHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("NewValue")
                        .HasColumnType("text");

                    b.Property<string>("OldValue")
                        .HasColumnType("text");

                    b.Property<int>("TaskId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId");

                    b.ToTable("TaskHistories");
                });

            modelBuilder.Entity("Kanban.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@test.com",
                            FullName = "Admin",
                            PasswordHash = "$2a$11$DEBJHZfJKIyA5Jcib/VvEexatn8Ye.yCDe5jYdl8uvhoejqUVSFy6",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "user@test.com",
                            FullName = "User 1",
                            PasswordHash = "$2a$11$AbYmJN3StqXRSMzkuo9kjeZq.tL.hN.ZtuBGIUILMH34zzDGN0/9u",
                            Role = "User"
                        },
                        new
                        {
                            Id = 3,
                            Email = "user2@test.com",
                            FullName = "User 2",
                            PasswordHash = "$2a$11$G3MkrF3XCfUQR6n1FEnkYOHfnRYRFBoww.2Tp1lOz.ggClAC0fbHi",
                            Role = "User"
                        },
                        new
                        {
                            Id = 999,
                            Email = "doc_js_galindo@fesc.edu.co",
                            FullName = "Docente FESC",
                            PasswordHash = "$2a$11$82gOG.bjzg0ovLhfyEXlBuaJHtBNuVXyg1.nO8T3S9PsLNAywA1yS",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("Kanban.Core.Entities.RefreshToken", b =>
                {
                    b.HasOne("Kanban.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kanban.Core.Entities.Task", b =>
                {
                    b.HasOne("Kanban.Core.Entities.User", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Kanban.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kanban.Core.Entities.User", null)
                        .WithMany("Tasks")
                        .HasForeignKey("UserId1");

                    b.Navigation("AssignedToUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kanban.Core.Entities.TaskHistory", b =>
                {
                    b.HasOne("Kanban.Core.Entities.Task", "Task")
                        .WithMany("History")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kanban.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kanban.Core.Entities.Task", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("Kanban.Core.Entities.User", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
